### ISSUE TITLE
Still actively developed? We would like to continue!

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/LieGroups.jl#4]
Hi,
very nice package idea you got started here.
We had some ideas about “groups on manifolds” already in Manifolds.jl https://juliamanifolds.github.io/Manifolds.jl/stable/manifolds/group.html for a while – I think we do cover the groups you have covered here,.
We now want to give them move focus by moving them to their own package, see https://github.com/JuliaManifolds/LieGroups.jl for w work-in-progress.

Would you maybe be willing to hand over the package name so we can continue your efforts to provide LieGroups to the Julia community? That would be awesome. We would of course mention that in the about page and you are of course more than welcome to contribute.

It is also not urgent, so please think about this for a while; we would still be super happy if we could use this name `LieGroups.jl` for our package.

Kind regards,
Ronny
(from the JuliaManifolds GitHub Org)

**Comment by kellertuer** [comment]
Hi @yuehhua,
I hope you are doing fine. This is just a short check, whether you have seen this already and maybe considered, whether it would be possible to continue this under the JuliaManifolds GitHub organisation umbrella?

**Comment by yuehhua** [comment]
Thank you for reminder. I missed the first issue and now I checked it. It's my pleasure to hand over the package name and even the package itself to community. If it helps community grow up, I am very willing to see that happens! Would it be good to transfer package to you? Or any other suggestions?

**Comment by kellertuer** [comment]
Woohow! Super great!

I already discussed that a bit on slack with people from the general registry.
My proposal is the following

* [x] we add an entry to our [News.md](https://github.com/JuliaManifolds/LieGroups.jl/blob/main/NEWS.md) where the name is from and where the previous versions are from
* [x] We would take over the UUID, then the next version 0.1.0 would just be a breaking change 
* [x]  You would be added to our [Project.toml](https://github.com/JuliaManifolds/LieGroups.jl/blob/main/Project.toml) as an author
* [x] You are of course super welcome as a developer, we can of course add you

If you have any other ideas we should take into account when transferring, let us know.

I discussed a bit with Michael @goerz and he proposed to even fork this repository do a delete-commit and rebase our project.
While I do see that this would make the connection even more visible (ours would forever be marked as a fork of this),
I feel that would be a bit complicated to do – what do you think about the approach? Do you feel fork/rebase is necessary? If so, we would of course try to do that as well.
A large disadvantage of the fork/rebase approach would be, that the issues we started and opened and PRs we did would be lost on the current repository on GitHub.

**Comment by kellertuer** [comment]
Hi again,
we discussed a bit with people from the General Registry and internally in @JuliaManifolds.

An idea is to keep the current history here. The best to do that is, to move this repository to our organisation, then add our new modelling to this repository.
That way it is really a breaking/rewrite release we do and it continues your history even.

If you add us (me and/or @mateuszbaran) here as admins, we can do that carefully. All other proposed mentions we would of course also do.

**Comment by yuehhua** [comment]
Sure! Feel free to add your model into the package. Maybe I just transfer this repo to you and you could move it into @JuliaManifolds. This could also keep the history in the repo and go on following development.

**Comment by kellertuer** [comment]
Oh, that was fast ;) I can check, I would maybe be easier to directly move it to JuliaManifolds, but sure, I can first move it to me, since before moving to JuliaManifolds we would also have to rename the ongoing WIP one linked above.

**Comment by kellertuer** [comment]
So we hopefully finished the rework.

**Comment by kellertuer** [comment]
@yuehhua thanks this was now super fast! I think we finished all things mentioned above. We will add a remark in the docs (probably the `about` page) as well for sure. If you feel there is a “transition manual” from your code to ours necessary as well, we can also do that; we do one to transition from Manifolds.jl anyways.

If otherwise everything is clarified here, we can also close this issue.

**Comment by yuehhua** [comment]
A "transition manual" sounds great! I am glad to hand over this package to whom really care about. Thank you so much!
